name: Deploy_Node_Application

on:
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        
      - name: Build Docker Image
        run: docker build -t ajinthomas619/picsaly-server .
        
      - name: Publish Image to Docker Hub
        run: docker push ajinthomas619/picsaly-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ajinthomas619/picsaly-server:latest
        
      - name: Run Docker container
        run: docker run -d -p 3000:3000  -e MONGO_PASSWORD= `${{secrets.MONGO_PASSWORD}}` ajinthomas619/picsaly-server:latest 
