name: Deploy_Node_Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: docker build -t ajinthomas619/picsaly-server/server -f docker/Dockerfile .

      - name: Publish Image to Docker Hub
        run: docker push ajinthomas619/picsaly-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ajinthomas619/picsaly-server:latest

      - name: Run Docker container
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        run: docker run -d -p 3000:3000 -e MONGO_PASSWORD=$MONGO_PASSWORD ajinthomas619/picsaly-server:latest
